/*

    Created: 2023-02-10
    Created by: Chavez Islas Jair
    Description: error management

*/

try{
    nonExistentFunction();
    let a = 3/0;
    console.log(a);
} catch(error){
    console.log(error)
}
consol.log(`Finalizado!!!!!1!!!!!1!!!11`)